---
- name: Update yum cache and upgrade packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install base packages
  yum:
    name:
      - git
      - unzip
      - ca-certificates
      - gnupg
      - python3-pip
      - wget
    state: present
