---
- name: Install Docker Engine
  yum:
    name:
      - docker
    state: present

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker Compose plugin
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ensure Docker cli-plugins directory exists
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Create docker-compose symlink for docker compose command
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    state: link
  ignore_errors: true
